Fix float comparison in unit test (#421)
Sometimes the floats aren't equal due to loss of precision, for example:
```
--- FAIL: TestResourceWithGatewaySum (0.00s)
    resources_test.go:31:
        	Error Trace:	/home/runner/work/tempo-operator/tempo-operator/internal/manifests/manifestutils/resources_test.go:31
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 1.0000001
        	Test:       	TestResourceWithGatewaySum
```
https://github.com/grafana/tempo-operator/actions/runs/5089699823/jobs/9147650291

Signed-off-by: Andreas Gerstmayr <agerstmayr@redhat.com>